### ISSUE TITLE
bug: production link is broken

### ISSUE THREAD

**Issue by aayushchugh** [hernandoabella/fancy-code-lines#1]
this link is broken: `https://code-lines.vercel.app/`

<img width="763" alt="image" src="https://github.com/hernandoabella/fancy-code-lines/assets/69336518/5e723c26-0f50-44a8-9084-106f26edae80">

**Comment by hernandoabella** [comment]
Fixed. 

This is the new link: https://fancy-code-lines.vercel.app/
